export const browserDemoModels = [
  {
    id: "bs-roformer-large-inst",
    name: "BS-Roformer Large Inst",
    architecture: "BS-Roformer",
    version: "2026.1",
    category: "instrumental",
    description: "Instrumental extraction tuned for modern mixes.",
    sdr: 17.61,
    fullness: 32.06,
    bleedless: 43.95,
    vram_required: 8,
    speed: "medium",
    stems: ["instrumental"],
    file_size: 0,
    installed: true,
    downloading: false,
    downloadProgress: 0,
    recommended: true,
    catalog_status: "verified",
    metrics_status: "guide_curated",
    card_metrics: {
      kind: "standard",
      primary_target: "instrumental",
      labels: ["SDR", "FULLNESS", "BLEED"],
      values: [17.61, 32.06, 43.95],
      source: "Guide 2026-03-04",
      evidence_note: "Guide-backed instrumental benchmark.",
      last_verified: "2026-03-04",
    },
    runtime: {
      allowed: ["msst"],
      preferred: "msst",
    },
    tags: ["instrumental", "quality"],
  },
  {
    id: "gabox-voc-fv7",
    name: "Gabox Voc FV7",
    architecture: "Mel-Roformer",
    version: "2026.1",
    category: "vocal",
    description: "Lead vocal extraction with strong bleed control.",
    sdr: 11.16,
    fullness: 17.99,
    bleedless: 33.85,
    vram_required: 8,
    speed: "medium",
    stems: ["vocals"],
    file_size: 0,
    installed: true,
    downloading: false,
    downloadProgress: 0,
    recommended: true,
    catalog_status: "verified",
    metrics_status: "guide_curated",
    card_metrics: {
      kind: "standard",
      primary_target: "vocals",
      labels: ["SDR", "FULLNESS", "BLEED"],
      values: [11.16, 17.99, 33.85],
      source: "Guide 2026-03-04",
      evidence_note: "Guide-backed vocal benchmark.",
      last_verified: "2026-03-04",
    },
    runtime: {
      allowed: ["msst"],
      preferred: "msst",
    },
    tags: ["vocal", "quality"],
  },
  {
    id: "mdx23c-drumsep-5stem",
    name: "MDX23C DrumSep 5-stem",
    architecture: "MDX23C",
    version: "1.0",
    category: "primary",
    description: "Kick, snare, toms, hi-hat and cymbals.",
    sdr: 16.66,
    fullness: 25.04,
    bleedless: 12.35,
    vram_required: 8,
    speed: "medium",
    stems: ["kick", "snare", "toms", "hihat", "cymbals"],
    file_size: 0,
    installed: false,
    downloading: false,
    downloadProgress: 0,
    recommended: false,
    catalog_status: "verified",
    metrics_status: "guide_curated",
    card_metrics: {
      kind: "special",
      primary_target: "drums",
      labels: ["KICK SDR", "SNARE FULL", "HH BLEED"],
      values: [16.66, 25.04, 12.35],
      source: "Guide 2026-03-04",
      evidence_note: "Guide-backed drum stem metrics.",
      last_verified: "2026-03-04",
    },
    runtime: {
      allowed: ["stemsep-legacy"],
      preferred: "stemsep-legacy",
    },
    tags: ["drumsep", "drums"],
  },
  {
    id: "small-karaoke-gaboxauf",
    name: "Small Karaoke GaboxAuf",
    architecture: "Mel-Roformer",
    version: "2026.1",
    category: "karaoke",
    description: "Compact karaoke model for browser preview and quick checks.",
    sdr: 0,
    fullness: 0,
    bleedless: 0,
    vram_required: 6,
    speed: "fast",
    stems: ["vocals", "instrumental"],
    file_size: 0,
    installed: true,
    downloading: false,
    downloadProgress: 0,
    recommended: false,
    catalog_status: "candidate",
    metrics_status: "missing_evidence",
    card_metrics: {
      kind: "status",
      primary_target: "karaoke",
      labels: ["METRICS", "DOWNLOAD", "RUNTIME"],
      values: ["Pending", "Direct", "Preview"],
      source: "Guide mention",
      evidence_note: "Numeric card metrics still pending.",
      last_verified: "2026-03-04",
    },
    runtime: {
      allowed: ["preview"],
      preferred: "preview",
    },
    tags: ["karaoke"],
  },
  {
    id: "anvuew-dereverb-bs-225050",
    name: "Anvuew Dereverb 22.5050",
    architecture: "BS-Roformer",
    version: "2026.1",
    category: "post_processing",
    description: "Mono dereverb tuned for spoken and vocal cleanup.",
    sdr: 22.505,
    fullness: 20.4,
    bleedless: 0,
    vram_required: 8,
    speed: "medium",
    stems: ["dereverb"],
    file_size: 0,
    installed: false,
    downloading: false,
    downloadProgress: 0,
    recommended: false,
    catalog_status: "verified",
    metrics_status: "guide_curated",
    card_metrics: {
      kind: "special",
      primary_target: "restoration",
      labels: ["MODEL SDR", "BASE SDR", "CHANNELS"],
      values: [22.505, 20.4, "Mono"],
      source: "Guide 2026-03-04",
      evidence_note: "Guide-highlighted dereverb release.",
      last_verified: "2026-03-04",
    },
    runtime: {
      allowed: ["msst"],
      preferred: "msst",
    },
    tags: ["restoration", "dereverb"],
  },
  {
    id: "mel-band-crowd",
    name: "Mel-Band Crowd",
    architecture: "Mel-Roformer",
    version: "preview",
    category: "primary",
    description: "Crowd extraction and cleanup preview card.",
    sdr: 0,
    fullness: 0,
    bleedless: 0,
    vram_required: 8,
    speed: "unknown",
    stems: ["decrowd", "denoise", "dereverb"],
    file_size: 0,
    installed: false,
    downloading: false,
    downloadProgress: 0,
    recommended: false,
    catalog_status: "manual_only",
    metrics_status: "missing_evidence",
    card_metrics: {
      kind: "status",
      primary_target: "restoration",
      labels: ["METRICS", "DOWNLOAD", "RUNTIME"],
      values: ["Pending", "Direct", "Manual"],
      source: "Catalog status",
      evidence_note: "Manual setup required outside desktop runtime.",
      last_verified: "2026-03-04",
    },
    runtime: {
      allowed: ["manual"],
      preferred: "manual",
    },
    tags: ["restoration", "denoise", "dereverb"],
  },
]
